### ISSUE TITLE
getMainLooper crash

### ISSUE THREAD

**Issue by jmir1** [Claudemirovsky/aniyomi-extensions-tester#3]
For some reason, the test fails with a "Stub!" error when trying to use `Looper.getMainLoper()`.
maybe this needs to be addressed in the androidcompat library? im not sure

![image](https://user-images.githubusercontent.com/43830312/201904156-27839119-f3f1-437d-8b86-44a864fc8555.png)

![image](https://user-images.githubusercontent.com/43830312/201904170-bb12e8e3-2f13-4a2d-95f2-9ad8f4781da7.png)

**Comment by Claudemirovsky** [comment]
As you said, the problem was in the AndroidCompat lib, [It was solved](https://github.com/Claudemirovsky/aniyomi-extensions-tester/commit/40af43085f69ec7fa086e02c1d6de932ec6b5fa5) with a little workaround using kotlin coroutines.

Unfortunately the test still gives a crash/false negative due to another similar problem, this time with the WebView implementation, but I'm already working on it 👍

**Comment by jmir1** [comment]
Nice 👍
